// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package main

import (
	"time"
)

type Mutation struct {
}

type NewTodoInput struct {
	Title       string  `json:"title"`
	Description *string `json:"description,omitempty"`
	UserID      string  `json:"userID"`
}

type Query struct {
}

// Todo is owned by this subgraph (todos-service).
type Todo struct {
	ID          string    `json:"id"`
	Title       string    `json:"title"`
	Description *string   `json:"description,omitempty"`
	Completed   bool      `json:"completed"`
	UserID      string    `json:"userID"`
	CreatedAt   time.Time `json:"createdAt"`
	UpdatedAt   time.Time `json:"updatedAt"`
}

func (Todo) IsEntity() {}

type UpdateTodoInput struct {
	Title       *string `json:"title,omitempty"`
	Description *string `json:"description,omitempty"`
	Completed   *bool   `json:"completed,omitempty"`
}

// User is a *foreign* entity (owned by users-service). This subgraph only
// contributes the `todos` field to it — a textbook Federation v2 entity
// extension, without touching the users table at all.
type User struct {
	ID    string  `json:"id"`
	Todos []*Todo `json:"todos"`
}

func (User) IsEntity() {}
